ALTER TABLE T_WC_T2S_PERSON
  ADD COLUMN PERSON_NAME_NORM VARCHAR(255)
  AS (
    LOWER(
      REGEXP_REPLACE(
        REGEXP_REPLACE(PERSON_NAME, '[^[:alnum:] ]', ' '), -- drop punctuation
        ' +', ' '                                   -- collapse spaces
      )
    )
  ) STORED;

CREATE INDEX IDX_T2S_PERSON_NAME_NORM ON T_WC_T2S_PERSON (PERSON_NAME_NORM);

ALTER TABLE T_WC_T2S_PERSON
  ADD COLUMN PERSON_NAME_KEY VARCHAR(255)
  AS (REPLACE(PERSON_NAME_NORM, ' ', '')) STORED;

CREATE INDEX IDX_T2S_PERSON_NAME_KEY ON T_WC_T2S_PERSON (PERSON_NAME_KEY);

ALTER TABLE T_WC_T2S_PERSON
  ADD FULLTEXT INDEX ft_person_name_norm (PERSON_NAME_NORM);
