ALTER TABLE T_WC_TMDB_PERSON_ALSO_KNOWN_AS
  ADD COLUMN PERSON_NAME_NORM VARCHAR(255)
  AS (
    LOWER(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          PERSON_NAME,
          '[^\\p{L}\\p{N} ]+',  ' '  -- keep Unicode letters/digits/spaces
        ),
        ' +', ' '                    -- collapse repeated spaces
      )
    )
  ) STORED;

ALTER TABLE T_WC_TMDB_PERSON_ALSO_KNOWN_AS
  ADD COLUMN PERSON_NAME_KEY VARCHAR(255)
  AS (REPLACE(PERSON_NAME_NORM, ' ', '')) STORED;
  
CREATE INDEX IDX_T2S_PERSON_NAME_NORM
  ON T_WC_TMDB_PERSON_ALSO_KNOWN_AS (PERSON_NAME_NORM);
 
CREATE INDEX IDX_T2S_PERSON_NAME_KEY
  ON T_WC_TMDB_PERSON_ALSO_KNOWN_AS (PERSON_NAME_KEY);
 
ALTER TABLE T_WC_TMDB_PERSON_ALSO_KNOWN_AS
  ADD FULLTEXT INDEX ft_person_name_norm (PERSON_NAME_NORM);
  